name: Main

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Checkout blender_279
        uses: actions/checkout@v3
        with:
          ref: blender_279
      - name: zip blender_279
        run:  mkdir ucupaint && rsync -av --exclude='.git/' --exclude='.github/' --exclude='ucupaint/' . ucupaint/ && zip -r ${{ github.event.repository.name }}-blender_279-legacy-${{ env.RELEASE_VERSION }}.zip ucupaint/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: ${{ github.event.repository.name }}-blender_279-legacy-${{ env.RELEASE_VERSION }}.zip
      - name: Checkout
        uses: actions/checkout@v3
      - name: zip
        run: mkdir ucupaint && rsync -av --exclude='.git/' --exclude='.github/' --exclude='ucupaint/' . ucupaint/ && zip -r ${{ github.event.repository.name }}-${{ env.RELEASE_VERSION }}.zip ucupaint/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: ${{ github.event.repository.name }}-${{ env.RELEASE_VERSION }}.zip
      - name: Checkout no-auto-update
        uses: actions/checkout@v3
        with:
          ref: no-auto-update
      - name: zip
        run: mkdir ucupaint && rsync -av --exclude='.git/' --exclude='.github/' --exclude='ucupaint/' . ucupaint/ && zip -r ${{ github.event.repository.name }}-no-auto-update-${{ env.RELEASE_VERSION }}.zip ucupaint/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: ${{ github.event.repository.name }}-no-auto-update-${{ env.RELEASE_VERSION }}.zip